apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 20Gi
