apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-model-extractor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-model-extractor
subjects:
- kind: ServiceAccount
  name: podman-model-extractor
  namespace: rag-tekton-lab
